#ifndef DEFINES_DISPLAY_H_
#define DEFINES_DISPLAY_H_

//DEFINES DISPLAY
#define DISPLAY_SIZE 960
#define DISPLAY_CENTRE DISPLAY_SIZE /2
#define SCALER 30
#define POS_X(x) ((x)* SCALER - SCALER/2)
#define POS_Y(y) ((y) * SCALER)

//DEFINES FONTS
#define FONT_SIZE 35
#define TITLE_SIZE 150
#define OPTIONS_SIZE 75

//DEFINES PARA MENU
#define TITLE_COLOR 254, 70, 165
#define BUTTON_COLOR 250, 218, 221
#define BUTTON_SEL_COLOR 233, 65, 150

// OPCIONES MENU
#define NEW_GAME 1
#define MAIN_MENU 2
#define HIGHSCORE 2
#define DIFFICULTY 3
#define QUIT 4

#endif /* DEFINES_DISPLAY_H_ */
